# Generated by Django 2.0.2 on 2018-03-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('time', models.DateTimeField()),
                ('content', models.TextField()),
            ],
        ),
    ]
