# Generated by Django 2.0.2 on 2018-03-28 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('area', models.CharField(max_length=64)),
                ('time', models.DateTimeField(default='2018-03-28')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemState',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('pwd', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='card_state', to='worksite.State'),
        ),
        migrations.AddField(
            model_name='item',
            name='chip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chip_state', to='worksite.State'),
        ),
        migrations.AddField(
            model_name='item',
            name='data',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='data_state', to='worksite.State'),
        ),
        migrations.AddField(
            model_name='item',
            name='grade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='grade_name', to='worksite.Grade'),
        ),
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='label_state', to='worksite.State'),
        ),
        migrations.AddField(
            model_name='item',
            name='predata',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='predata_state', to='worksite.State'),
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='status_state', to='worksite.ItemState'),
        ),
    ]
