# Generated by Django 2.0.2 on 2018-03-07 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worksite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=12)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='data',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='data_state', to='worksite.State'),
        ),
        migrations.AddField(
            model_name='item',
            name='handle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='handle_state', to='worksite.State'),
        ),
    ]
