# Generated by Django 2.0.2 on 2018-03-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='time',
            field=models.DateTimeField(default='2018-03-29'),
        ),
    ]
