# Generated by Django 2.0.2 on 2018-03-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksite', '0002_auto_20180307_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='area',
            field=models.CharField(default='1', max_length=64),
            preserve_default=False,
        ),
    ]
