# Generated by Django 2.0.2 on 2018-03-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksite', '0003_item_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
