# Generated by Django 2.0.2 on 2018-03-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksite', '0004_auto_20180314_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('pwd', models.CharField(max_length=64)),
            ],
        ),
    ]
