# Generated by Django 2.0.2 on 2018-03-16 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksite', '0005_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
