# Generated by Django 2.0.2 on 2018-03-16 01:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('worksite', '0006_auto_20180316_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
