# Generated by Django 2.0.2 on 2018-03-16 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksite', '0007_auto_20180316_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 16, 10, 2, 58, 663680)),
        ),
    ]
